spring:
  application:
    name: gateway

server:
  port: 1003

zuul:
  routes:
    user-management:
      path: /user-management/**
      serviceId: user-management

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
